#source: http://wiki.ubuntu.org.cn/%E8%B7%9F%E6%88%91%E4%B8%80%E8%B5%B7%E5%86%99Makefile:MakeFile%E4%BB%8B%E7%BB%8D

test:
	./node_modules/.bin/mocha

cov test-cov:
	./node_modules/.bin/istanbul cover _mocha

.PHONY: test cov test-cov
